FROM ubuntu
MAINTAINER Jose Julian
RUN apt-get update
RUN apt-get install -y apache2

RUN echo "<h1>Apache desde Docker</h1>" > /var/www/html/index.html

EXPOSE 80
ENTRYPOINT apache2ctl -D FOREGROUND	

